title: Test Blog
author: Aurore
email: 
description: > # this means to ignore newlines until "baseurl:"
  This page is a test page. Later on, I will create and maintain a blog about
  my ongoing projects. I’m interested in linguistics, analytics and machine learning.
  I’m currently using R as my main programing tool.

# social links
twitter_username: borealll
github_username:  Aurare

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
